name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      libraryName: tensorflow
      installationPath: tensorflow-installation
      tagName: v2.6.0
      mingwTargetZip: tensorflow-${{ github.ref_name }}-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/tensorflow/tensorflow.git && cd tensorflow && git checkout -f  ${{ env.tagName }}
        
      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run: |
          curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe &&^
          dir &&^
          7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"PortableGit-2.38.1-64-bit"
        
      - name: curl python-3.7.9-amd64-portable.zip
        shell: cmd
        run: |
          curl https://github.com/dirkarnez/python-portable/releases/download/v3.8.10/python-3.8.10-amd64-portable.zip -L --output python-3.8.10-amd64-portable.zip &&^
          dir &&^
          7z.exe x python-3.8.10-amd64-portable.zip -o"python-3.8.10-amd64-portable"
          
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          
      - name: curl bazel
        shell: cmd
        run: |
          curl https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-windows-x86_64.exe -L --output bazel.exe
      
      - name: temp
        shell: cmd
        run: |
          cd /d "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" &&^
          dir /s
          
      - name: MSVC build
        shell: msys2 {0}
        run: |
            export workspace=$(pwd) && \
            cp "$workspace/bazel.exe" /mingw64/bin/ && \
            export BAZEL_VC="/C/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/16.11.33027.164/bin/Hostx64/x64" && \
            cd "$BAZEL_VC" && \
            ls && \
            cd "$workspace/tensorflow" && \
            export PATH="/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" && \
            export PATH="$workspace/python-3.8.10-amd64-portable:$workspace/python-3.8.10-amd64-portable/Scripts:$PATH" && \
            export PATH="$workspace/PortableGit-2.38.1-64-bit/bin:$PATH" && \
            export MSYS_NO_PATHCONV=1 && \
            export MSYS2_ARG_CONV_EXCL="*" && \
            pacman --noconfirm -S patch unzip && \
            python -m pip install numpy && \
            python ./configure.py && \
            bazel build -c opt --copt=/arch:AVX --announce_rc --config=opt --define=no_tensorflow_py_deps=true  //tensorflow/tools/lib_package:libtensorflow --verbose_failures
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "tensorflow/bazel-bin"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tensorflow/bazel-bin/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
